name: Manually release

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      name:
        description: 'Release Name'
        required: true
        default: '0.0.0'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Publish the Docker image
        run: |
          suffix=$(date +%s)
          docker build -t ghcr.io/datapunchorg/helm-hive-metastore:main-$suffix docker
          docker push ghcr.io/datapunchorg/helm-hive-metastore:main-$suffix
